### ISSUE TITLE
warblerfunctions.R isn't used

### ISSUE THREAD

**Issue by goldingn** [oharar/IM_warbler#9]
...as far as I can tell. The functions it contains are all replicated in other function files, and every instance of warblerfunctions.R being sourced is commented out. Best to remove it to avoid confusing the reader.

I suggest deleting it from the repo, scripts, and readme. Though creating a PR to do so now would conflict with the open PRs, so best wait until those are merged in.

**Comment by oharar** [comment]
Done. Thanks!
